### PR TITLE
Community website screenshot

### PR DESCRIPTION
**Pull request by WebShivam**
#ISSUE-NO
#234

#### What does this PR do?
This PR adds a screenshot of the homepage of Community Website

### CODE REVIEW

**Comment by namangupta1399** [comment]
@WebShivam , please give some meaningful name to the screenshot file, so that it is easily distinguishable when we add other images to the directory.

Thanks

**Comment by namangupta1399** [comment]
The new file is not visible. Did you rename the file or delete it ?

**Review by WebShivam — COMMENTED** [review]
As you asked me I renamed the image, Looking forward to get the PR merged now

**Comment by WebShivam** [comment]
> The new file is not visible. Did you rename the file or delete it ?

I renamed it and its new name is `community-website-screenshot`

**Review by schmelto — APPROVED** [review]
Lgtm

**Pull request merged**
