### PR TITLE
Added Project Section

### PR DESCRIPTION
**Pull request by Evavic44**
#ISSUE-NO
#232 

#### What does this PR do?
Add project section to community website

#### Description of Task to be completed?
Fix the following issues:
- [x] #233 
- [ ] #234 
#### How can this be manually tested?
Local host

#### Any background context you want to provide?
Not responsive on mobile view
#### What is the relevant issue link?
#232

### CODE REVIEW

**Comment by namangupta1399** [comment]
Nice work @Evavic44 

Pls check this. 
Animation

I  think it can be prevented if you set the z-index of the project div

**Comment by schmelto** [comment]
Does it make sense to use the GitHub api to get the projects with all data?

**Comment by schmelto** [comment]
One other suggestion maybe you can use flex ox to make it responsive

I mostly use something like this:

```css
.flex-col-2 { width: 100%; height: auto; columns: 2;}
```

**Comment by Evavic44** [comment]
> Nice work @Evavic44
> 
> Pls check this.
> Animation
> 
> I think it can be prevented if you set the z-index of the project div

Thanks for pointing that out, didn't scroll the project section past the navbar.

**Comment by Evavic44** [comment]
> Does it make sense to use the GitHub API to get the projects with all data?
> 
> I`ve implemented that to my portfolio website here
> https://github.com/schmelto/portfolio/blob/09c68f9677c33fa90461bb7c9e73052c38279cfe/js/scripts.js#L91
> 
> This would look something like this
> 
> ```js
> let githubprojects = [
>   {
>     name: 'schmelto/portfolio',
>     icon: 'person',
>   },
>   {
>     name: 'chryz-hub/chryz-hub.github.io',
>     icon: 'home',
>   },
> ];
> ```
> 
> ```js
> function getproject(project, icon) {
>   fetch(`https://api.github.com/repos/${project}`)
>     .then((response) => {
>       return response.json();
>     })
>     .then((project) => {
>       githubprojectsdomelement.innerHTML += createprojectcard(project, icon);
>     });
> }
> 
> function createprojectcard(project, icon) {
>   // add html elements
> }
> ```
> 
> some more references can be found here https://docs.github.com/en/rest/reference/repos

I like this idea, so we won't have to constantly maintain this or add more projects.

**Comment by Evavic44** [comment]
One question though, is there a way to automatically add the background image as well?

**Comment by namangupta1399** [comment]
> One question though, is there a way to automatically add the background image as well?

For that I think we can pass the source for background image just like the icon. Or we can find other ways.

**Comment by schmelto** [comment]
> For that I think we can pass the source for background image just like the icon. Or we can find other ways.

The other way could be to use the social preview image of the repo itself don't know if the API sends this by itself

**Comment by namangupta1399** [comment]
> > For that I think we can pass the source for background image just like the icon. Or we can find other ways.
> 
> The other way could be to use the social preview image of the repo itself don't know if the API sends this by itself

Yeah, it would be great if it works

**Comment by Evavic44** [comment]
> 
> > For that I think we can pass the source for background image just like the icon. Or we can find other ways.
> 
> The other way could be to use the social preview image of the repo itself don't know if the API sends this by itself 

Okay, so what next?  Should I merge this so you can write the code?.

**Comment by schmelto** [comment]
> Okay, so what next?  Should I merge this so you can write the code? 

I leave it open for someone else we can make a new issue out of this?

**Comment by schmelto** [comment]
One other question is this a copyright free image?
and I think @Evavic44 the problem with the z-index is still open?

**Comment by Evavic44** [comment]
> One other question is this a copyright free image?
> and I think @Evavic44 the problem with the z-index is still open?

Okay, I'll fix the z-index issue and then create another PR. The image is just some random image I saw online, maybe will delete it for now or use a free photo from `Pexels` or `Unsplash`.

**Pull request merged**
