### PR TITLE
All minor recent issue solved

### PR DESCRIPTION
**Pull request by AmjadNoor**
## ISSUE-NO
#140 
#141 
#142 
#143 
## Description
Changes done according to above issues.
Thanks 😊.

### CODE REVIEW

**Comment by Evavic44** [comment]
Hello @AmjadNoor, thanks for your contributions but can you please do only one issue, so others can contribute as well.  😎

**Comment by AmjadNoor** [comment]
@Evavic44 merge it because it is a minor changes and in future I will left some issue for others. I don't know how to revert merge changes in fork repo. I think we have to first drop the issues in discord(Ola also mentioned this in Discord) and people choose what they want it will help all of us.

**Comment by AmjadNoor** [comment]
If you know about how to revert merge changes then don't merge this PR and tell me how to revert changes I will revert it.

**Comment by sifa123** [comment]
@AmjadNoor please check this link https://www.youtube.com/watch?v=ml2N3APdoB0 . Hope this will help you :smiley:

**Comment by Evavic44** [comment]
> @Evavic44 merge it because it is a minor changes and in future I will left some issue for others. I don't know how to revert commit changes.
> 
> I think we have to first drop the issues in discord(Ola also mentioned this in Discord) and people choose what they want it will help all of us.

Yeah, I agree.

**Comment by Evavic44** [comment]
> @AmjadNoor please check this link https://www.youtube.com/watch?v=ml2N3APdoB0 . Hope this will help you 😃

Thanks @sifa123 for sharing. @AmjadNoor hope this helps.

**Pull request closed without merging**
