### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by blackkolanut**
#ISSUE-NO

### CODE REVIEW

**Comment by blackkolanut** [comment]
Added my name to the contributors list

**Review by chryzcodez — CHANGES_REQUESTED** [review]
The place where you added your name was used as an example for people.

So, you have to remove your name and link from where you placed it first and create yours and add it alphabetically .

Thanks!

**Comment by jomefavourite** [comment]
> The place where you added your name was used as an example for people.
> 
> So, you have to remove your name and link from where you placed it first and create yours and add it alphabetically .
> 
> Thanks!

**Comment by jomefavourite** [comment]
I'll help fix it

**Pull request merged**
