### PR TITLE
Mobile menu

### PR DESCRIPTION
**Pull request by IbrahimOlayinka**
#187 

#### What does this PR do?
         Added hamburger menu for mobile responsiveness

#### Screenshots (if appropriate)
        
chryz-mobile

### CODE REVIEW

**Comment by jomefavourite** [comment]
Thanks for contributing, it looks okay to me. 
@Evavic44 what do you think?

**Review by schmelto — APPROVED** [review]

**Comment by namangupta1399** [comment]
hey @schmelto, nicely done 👍 

Please check this gap
Mobile view

**Comment by Evavic44** [comment]
> hey @schmelto, nicely done 👍
> 
> Please check this gap
> Mobile view

The navbar looks cool. Do you know what's causing this spacing? @IbrahimOlayinka Please have a look. Thanks for the changes. 😎

**Comment by IbrahimOlayinka** [comment]
ok i will have a look at what's causing gap.

**Comment by IbrahimOlayinka** [comment]
Ok, i noticed the open gap, and have fixed it, check it out.
chryz-mobile-space

chryz-mobile-close-gap

**Review by Evavic44 — COMMENTED** [review]
Thank you for your PR's. I tested it out and here are a few things I noticed: 
- [ ] The transition of the hamburger menu shows up when reducing the width of the page.
- [ ] The hamburger menu doesn't close up when you click the links 
_Watch this gif for more clarity_
gif-php

**Comment by IbrahimOlayinka** [comment]
@Evavic44 have fixed the bug with the hamburger menu transition pop up

**Comment by Evavic44** [comment]
> @Evavic44 have fixed the bug with the hamburger menu transition pop up

LGTM! 👍🏾

**Comment by namangupta1399** [comment]
@IbrahimOlayinka , pls fetch the latest code from original repo. to prevent conflicts.

**Comment by Evavic44** [comment]
> @IbrahimOlayinka , pls fetch the latest code from original repo. to prevent conflicts.

I already fixed the conflicts.

**Comment by namangupta1399** [comment]
Great. We are good to go 💯

**Comment by Evavic44** [comment]
> Great. We are good to go 💯

You can go ahead and merge it @namangupta1399 👍🏾

**Pull request merged**
