### PR TITLE
Changed how links worked

### PR DESCRIPTION
**Pull request by pranavbaburaj**
Changed how links worked and formatted the code

### CODE REVIEW

**Comment by jomefavourite** [comment]
Nicely done @pranavbaburaj, thanks for contributing to the community.

May I ask why you implement it this way?

**Comment by pranavbaburaj** [comment]
> Nicely done @pranavbaburaj, thanks for contributing to the community.
> 
> May I ask why you implement it this way?

It helps us change the behavior of links. Links associated with the same page(href starting with a `.`) are opened in the same tab and all the other links all opened in a new tab.

It helps to open links in a separating tab without distracting the user

**Comment by Evavic44** [comment]
Thank you @pranavbaburaj for contributing to this project, we value everyone's input at Chryz-hub, which is why we drafted a [Contribution Guideline](https://github.com/chryz-hub/chryz-hub.github.io/blob/master/CONTRIBUTING.md) we advise every member looking to contribute should go through before making a PR.

**Comment by jomefavourite** [comment]
> > Nicely done @pranavbaburaj, thanks for contributing to the community.
> > May I ask why you implement it this way?
> 
> It helps us change the behavior of links. Links associated with the same page(href starting with a `.`) are opened in the same tab and all the other links all opened in a new tab.
> 
> It helps to open links in a separating tab without distracting the user

Okay, I think I know why you made it so now 👍

**Comment by chryzcodez** [comment]
So @Evavic44 @jomefavourite @namangupta1399 what do you see concerning this pull request.

**Comment by Evavic44** [comment]
> So @Evavic44 @jomefavourite @namangupta1399 what do you see concerning this pull request.

I think it's okay but for a better workflow, the best thing is to raise an issue first for each change. Will be easier to review that way.

**Comment by jomefavourite** [comment]
> So @Evavic44 @jomefavourite @namangupta1399 what do you see concerning this pull request. 

To me, I think the PR is okay,it's just to fix the conflicts

**Review by namangupta1399 — APPROVED** [review]
LGTM 👍

**Comment by chryzcodez** [comment]
please @pranavbaburaj can you make this pull request again because there are already conflict. Sorry for the delay.

**Comment by Evavic44** [comment]
> 
> 
> please @pranavbaburaj can you make this pull request again because there are already conflict. Sorry for the delay.

We can still fix the conflicts. Lemme try

**Comment by pranavbaburaj** [comment]
> please @pranavbaburaj can you make this pull request again because there are already conflict. Sorry for the delay.

But, I actually deleted the forked repo 🤦🏾‍♂️

**Comment by chryzcodez** [comment]
> > please @pranavbaburaj can you make this pull request again because there are already conflict. Sorry for the delay.
> 
> But, I actually deleted the forked repo 🤦🏾‍♂️

Oh!!!

sorry, I have to close this, then;

**Pull request closed without merging**
