### PR TITLE
Merged Conflict

### PR DESCRIPTION
**Pull request by Evavic44**
#ISSUE-NO

### CODE REVIEW

**Comment by Evavic44** [comment]
@chryzcodez Please I had conflict issues with my forked repo.

**Comment by AmjadNoor** [comment]
@Evavic44 I had also conflict issues with my forked repo. Finally I deleted the forked repo and re-forked it.

**Comment by Evavic44** [comment]
@AmjadNoor It's frustrating. Now I don't wanna make any more changes before I'll have more conflicts like;
`This branch is 5 commits ahead` `This branch is 3 commits behind` at the same time. 😢

**Comment by chryzcodez** [comment]
Okay, I 've replied you in the the discord server!

**Review by chryzcodez — APPROVED** [review]

**Pull request merged**
