### PR TITLE
docs: improved the readme for contributing to the community website

### PR DESCRIPTION
**Pull request by jomefavourite**
#ISSUE-NO

#### What does this PR do?
Improves the Readme file

### CODE REVIEW

**Review by chryzcodez — APPROVED** [review]

**Review by Evavic44 — COMMENTED** [review]
Cool changes. Thanks @jomefavourite.
> ### Review

1. I feel The Community website README should elaborate more on the community website since this is the repo it lives in with information like: `The vision statement`, `What the community is all about`, `How to join the community` `Relevant links of the community`, and not really elaborate on how to make a PR since we already have a [How to contribute](https://github.com/chryz-hub/opensource-4-everyone#simple-guide-to-making-a-pull-request-or-contribution) markdown file. 
2. Screenshot of our community website.
3. If possible a moderators section with images of the moderators of the community.
The texts should be short and simple to read so viewers don't get bored and end up not reading it.

**Comment by jomefavourite** [comment]
> Cool changes. Thanks @jomefavourite.
> > ### Review
> 
> 1. I feel The Community website README should elaborate more on the community website since this is the repo it lives in with information like: `The vision statement`, `What the community is all about`, `How to join the community` `Relevant links of the community`, and not really elaborate on how to make a PR since we already have a [How to contribute](https://github.com/chryz-hub/opensource-4-everyone#simple-guide-to-making-a-pull-request-or-contribution) markdown file. 
> 2. Screenshot of our community website.
> 3. If possible a moderators section with images of the moderators of the community.
> The texts should be short and simple to read so viewers don't get bored and end up not reading it. 

Okay then, I'll make other changes.

**Review by namangupta1399 — COMMENTED** [review]
Great job @jomefavourite

**Comment by Evavic44** [comment]
I can't view the source `diff` so I'll leave the review to @namangupta1399 and @chryzcodez

**Comment by namangupta1399** [comment]
image
It should be either `git push` or `git push origin <your branch name>`
@jomefavourite

**Comment by jomefavourite** [comment]
> image
> It should be either `git push` or `git push origin <your branch name>`
> @jomefavourite

My bad, I'll also fix that

**Comment by namangupta1399** [comment]
@jomefavourite , any update on the fixes ?

**Comment by jomefavourite** [comment]
> @jomefavourite , any update on the fixes ?

Oh not yet, I'll make changes soon

**Pull request merged**
