### PR TITLE
Update lighthouse.yml

### LINKED ISSUE #237: Lighthouse check action not working properly
https://github.com/chryz-hub/chryz-hub.github.io/runs/2639747905?check_suite_focus=true

I think the problem is in this step https://github.com/chryz-hub/chryz-hub.github.io/blob/4b7c5dc1327601e0fb30e6b68f891d1d314f7b21/.github/workflows/lighthouse.yml#L15

```
2021-05-21T13:37:57.1953413Z From https://github.com/chryz-hub/chryz-hub.github.io
2021-05-21T13:37:57.1954370Z  * [new branch]      master              -> origin/master
2021-05-21T13:37:57.1955172Z  * [new branch]      website             -> origin/website
2021-05-21T13:37:57.1956009Z  * [new ref]         refs/pull/225/merge -> pull/225/merge
2021-05-21T13:37:57.1957180Z ##[command]git checkout --progress --force refs/remotes/pull/225/merge
2021-05-21T13:37:57.1958109Z Note: switching to 'refs/remotes/pull/225/merge'.
2021-05-21T13:37:57.1958555Z 
2021-05-21T13:37:57.1959333Z You are in 'detached HEAD' state. You can look around, make experimental
2021-05-21T13:37:57.1960171Z changes and commit them, and you can discard any commits you make in this
2021-05-21T13:37:57.1960973Z state without impacting any branches by switching back to a branch.
2021-05-21T13:37:57.1961476Z 
2021-05-21T13:37:57.1962040Z If you want to create a new branch to retain commits you create, you may
2021-05-21T13:37:57.1962971Z do so (now or later) by using -c with the switch command. Example:
2021-05-21T13:37:57.1963446Z 
2021-05-21T13:37:57.1964001Z   git switch -c <new-branch-name>
2021-05-21T13:37:57.1964319Z 
2021-05-21T13:37:57.1964679Z Or undo this operation with:
2021-05-21T13:37:57.1964954Z 
2021-05-21T13:37:57.1965588Z   git switch -
2021-05-21T13:37:57.1965929Z 
2021-05-21T13:37:57.1966522Z Turn off this advice by setting config variable advice.detachedHead to false
2021-05-21T13:37:57.1967098Z 
2021-05-21T13:37:57.1967992Z HEAD is now at 817b809 Merge 3b8bf0cca78b5315fb0c95b34eeafa30b3104da0 into 554f2b7e6102d42f4b46529313bbef630e73e947
2021-05-21T13:37:57.2151691Z ##[group]Run foo-software/lighthouse-check-action@v2.0.5
2021-05-21T13:37:57.2152255Z with:
2021-05-21T13:37:57.2153682Z   accessToken: ***
2021-05-21T13:37:57.2154247Z   urls: https://chryz-hub.github.io/
2021-05-21T13:37:57.2154791Z ##[endgroup]
2021-05-21T13:37:58.0314947Z [@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
2021-05-21T13:37:58.0316766Z lighthouse-check: Auditing mobile (1/1): https://chryz-hub.github.io/
2021-05-21T13:38:07.5828498Z lighthouse-check: LighthouseCheckError: Resource not accessible by integration
2021-05-21T13:38:07.5831257Z     at _default (/home/runner/work/_actions/foo-software/lighthouse-check-action/v2.0.5/node_modules/@foo-software/lighthouse-check/dist/postPrComment.js:119:13)
2021-05-21T13:38:07.5834676Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-05-21T13:38:07.5836662Z     at async /home/runner/work/_actions/foo-software/lighthouse-check-action/v2.0.5/node_modules/@foo-software/lighthouse-check/dist/lighthouseCheck.js:201:11 {
2021-05-21T13:38:07.5838022Z   code: 'ERROR_UNEXPECTED_RESPONSE',
2021-05-21T13:38:07.5838510Z   data: {
2021-05-21T13:38:07.5839209Z     message: 'Resource not accessible by integration',
2021-05-21T13:38:07.5840683Z     documentation_url: 'https://docs.github.com/rest/reference/pulls#create-a-review-for-a-pull-request'
2021-05-21T13:38:07.5841700Z   }
2021-05-21T13:38:07.5842027Z }
2021-05-21T13:38:07.5854153Z lighthouse-check:
2021-05-21T13:38:07.5855295Z  LighthouseCheckError: Resource not accessible by integration
2021-05-21T13:38:07.5857022Z     at _default (/home/runner/work/_actions/foo-software/lighthouse-check-action/v2.0.5/node_modules/@foo-software/lighthouse-check/dist/postPrComment.js:119:13)
2021-05-21T13:38:07.5858499Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-05-21T13:38:07.5860233Z     at async /home/runner/work/_actions/foo-software/lighthouse-check-action/v2.0.5/node_modules/@foo-software/lighthouse-check/dist/lighthouseCheck.js:201:11 {
2021-05-21T13:38:07.5861938Z   code: 'ERROR_UNEXPECTED_RESPONSE',
2021-05-21T13:38:07.5862550Z   data: {
2021-05-21T13:38:07.5864121Z     message: 'Resource not accessible by integration',
2021-05-21T13:38:07.5865478Z     documentation_url: 'https://docs.github.com/rest/reference/pulls#create-a-review-for-a-pull-request'
2021-05-21T13:38:07.5866372Z   }
2021-05-21T13:38:07.5867358Z }
2021-05-21T13:38:07.5872515Z ##[error]Resource not accessible by integration
2021-05-21T13:38:07.6100208Z Cleaning up orphan processes
```

### PR DESCRIPTION
**Pull request by schmelto**
resolve #237 

this should resolve this issue

### CODE REVIEW

**Comment by schmelto** [comment]
IT could also be a problem with the authorization (see something like [here](https://github.com/actions/first-interaction/issues/10))

**Comment by schmelto** [comment]
@chryzcodez couldyou take a look at this
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#:~:text=About%20the%20GITHUB_TOKEN%20secret,-GitHub%20automatically%20creates&text=The%20GITHUB_TOKEN%20secret%20is%20a,repository%20that%20contains%20your%20workflow.

**Comment by Evavic44** [comment]
> IT could also be a problem with the authorization (see something like [here](https://github.com/actions/first-interaction/issues/10))

Wow, just read through it. Is there like a fix for this?

**Comment by schmelto** [comment]
> > IT could also be a problem with the authorization (see something like [here](https://github.com/actions/first-interaction/issues/10))
> 
> Wow, just read through it. Is there like a fix for this?

I'm not completely sure think this could be done via a setting in the repo settings I've methioned @chryzcodez above

**Comment by Evavic44** [comment]
> > > IT could also be a problem with the authorization (see something like [here](https://github.com/actions/first-interaction/issues/10))
> > 
> > 
> > Wow, just read through it. Is there like a fix for this?
> 
> I'm not completely sure think this could be done via a setting in the repo settings I've methioned @chryzcodez above

Okay. 👍🏾

**Comment by schmelto** [comment]
@chryzcodez i think I found the issue it might be because of the GitHub secret can you add another one s the actions tönt complain with each other I think you can only use one secret / token for one action

**Pull request closed without merging**
