### PR TITLE
Added right arrow to Read more button

### PR DESCRIPTION
**Pull request by Evavic44**
#ISSUE-NO

#### What does this PR do?
Adds fontawesome right arrow to `Read More` button

#### How can this be manually tested?
Local host

### CODE REVIEW

**Review by schmelto — COMMENTED** [review]
image
Looking good.

One thing personally I would consider that this function like a dopdown so that the vision text will collabs after clicking and not redirecting to github md file

**Comment by chryzcodez** [comment]
Yeah, that was truly said. It shouldn't lead to github. It should display the remaining wordings of the sentence.

**Comment by namangupta1399** [comment]
This is looking good @Evavic44 . 👍

**Comment by Evavic44** [comment]
> image
> Looking good.
> 
> One thing personally I would consider that this function like a dopdown so that the vision text will toggle after clicking and not redirecting to github md file

I like this idea. We'll create a new issue for the drop-down section.

**Comment by Evavic44** [comment]
> This is looking good @Evavic44 . 👍
> Should we create a separate issue for data toggle part ?

Yes. That means I'll have to change the icon to a down arrow. 👌🏽

**Review by Evavic44 — COMMENTED** [review]
Added animation to the right arrow to rotate to a down arrow on hover.  I think this is better.
**Issue Link: #191** 
Here is a preview 👇🏾 Give feedback guys so we can merge this.
right-arrow-hover

**Comment by namangupta1399** [comment]
@Evavic44, can you do something about the color of arrow when it loads initially
Animation

**Comment by Evavic44** [comment]
> @Evavic44, can you do something about the color of arrow when it loads initially
> Animation

Oh... Well you can go ahead and create a new issue for this.

**Pull request merged**
