### PR TITLE
Order files

### PR DESCRIPTION
**Pull request by Evavic44**
#ISSUE-NO #256

#### What does this PR do?
Organize folders as agreed.

#### Description of Task to be completed?
None
#### How can this be manually tested?
Local host.
#### Any background context you want to provide?
None
#### What is the relevant issue link?
#256 
#### Questions:
Are we comfortable with this structure?

### CODE REVIEW

**Review by jomefavourite — APPROVED** [review]
Perfecto

**Comment by jomefavourite** [comment]
Oh, I shouldn't have merged it yet. 
I'm sorry for not waiting for others reviews.

Also, I just noticed you didn't follow exactly the structure provided by @schmelto 

But @schmelto and everyone is this new structure okay?

Once again, I'm sorry for merging it without thoroughly checking

**Comment by Evavic44** [comment]
> 
> 
> Oh, I shouldn't have merged it yet.
> I'm sorry for not waiting for others reviews.
> 
> Also, I just noticed you didn't follow exactly the structure provided by @schmelto
> 
> But @schmelto and everyone is this new structure okay?
> 
> Once again, I'm sorry for merging it without thoroughly checking

It's alright Jome. We can still update it accordingly. @schmelto and @namangupta1399 what do you think, is this structure okay?

**Comment by namangupta1399** [comment]
I think what @schmelto  meant was moving the **index.html** in the **src** folder. Then changing **gh-pages** settings to use **src** folder for deployment of the website.
Like this

- src
   - index.html
   - assets
        - img1.png
        - img2.png
   - js
        - script.js
   - css
        - style.css
        
Is this fine, @schmelto ?

**Comment by schmelto** [comment]
> I think what @schmelto  meant was moving the **index.html** in the **src** folder. Then changing **gh-pages** settings to use **src** folder for deployment of the website.
> Like this
> 
> - src
>    - index.html
>    - assets
>         - img1.png
>         - img2.png
>    - js
>         - script.js
>    - css
>         - style.css
>         
> Is this fine, @schmelto ?

Yes

**Comment by schmelto** [comment]
@Evavic44 i suggest using closes #issuenumber in the pr description thus it link the issue better to the pr

**Comment by chryzcodez** [comment]
Yeah, truly said.

**Comment by Evavic44** [comment]
> 
> 
> @Evavic44 i suggest using closes #issuenumber in the pr description thus it link the issue better to the pr

Yeah, I didn't know it wasn't added. Will fix that.

**Comment by Evavic44** [comment]
> 
> 
> I think what @schmelto meant was moving the **index.html** in the **src** folder. Then changing **gh-pages** settings to use **src** folder for deployment of the website.
> Like this
> 
>     * src
>       
>       * index.html
>       * assets
>         
>         * img1.png
>         * img2.png
>       * js
>         
>         * script.js
>       * css
>         
>         * style.css
> 
> 
> Is this fine, @schmelto ?

Okay, now I understand. Will fix that ASAP

**Pull request merged**
